# Generated by Django 3.1.8 on 2021-08-02 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multimedia.sub_models.media


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='multimedia.multimedia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=multimedia.sub_models.media.upload_video_to, validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv', 'mov', 'MOV'])], verbose_name='Multimedia Video File'),
        ),
    ]
