# Generated by Django 3.1.8 on 2021-08-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_auto_20210807_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='type',
            field=models.CharField(choices=[('satsang', 'Satsang'), ('prayer', 'Prayer'), ('testimonial', 'Testimonial'), ('bhajan', 'Bhajan')], default='satsang', max_length=11),
        ),
    ]
