# Generated by Django 3.1.8 on 2021-08-02 20:01

import django.core.validators
from django.db import migrations, models
import event.sub_models.event_media


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvideo',
            name='video',
            field=models.FileField(upload_to=event.sub_models.event_media.upload_event_video_to, validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv', 'mov', 'MOV'])]),
        ),
    ]
