# Generated by Django 3.1.8 on 2021-09-19 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0002_auto_20210803_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[(0, 'Custom Detail'), (1, 'Anonymously'), (2, 'Login')], default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='writer_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Should be a registered Nepal phone number.', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='feedback',
            name='writer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='writer_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='writer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
