# Generated by Django 3.1.8 on 2021-09-19 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0003_auto_20210919_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
