# Generated by Django 3.1.8 on 2021-09-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_auto_20210919_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('0', 'Custom Detail'), ('1', 'Anonymously'), ('2', 'Login')], max_length=13),
        ),
    ]
